name: Deploy Portfolio Website

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: portfolio-website
          path: dist/

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: portfolio-website
          path: dist
          
      - name: AWS Login
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: github-actions-session
          aws-region: ap-southeast-2

      - name: Deploy to S3
        run: |
          aws s3 sync dist/_astro/ s3://${{ secrets.S3_BUCKET }}/_astro/ \
            --cache-control "public, max-age=31536000, immutable" \
            --delete
          
          aws s3 sync dist/fonts/ s3://${{ secrets.S3_BUCKET }}/fonts/ \
            --cache-control "public, max-age=31536000, immutable" \
            --delete
          
          aws s3 sync dist/ s3://${{ secrets.S3_BUCKET }}/ \
            --exclude "_astro/*" \
            --exclude "fonts/*" \
            --cache-control "public, max-age=3600" \
            --delete

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/*"
        